Changes to satisfy shellcheck

diff --git a/ate_sources.d/ate_exit_on_error b/ate_sources.d/ate_exit_on_error
--- a/ate_sources.d/ate_exit_on_error
+++ b/ate_sources.d/ate_exit_on_error
@@ -1,12 +1,16 @@
-# -*- mode:sh -*-
+# -*- mode:shell-script; sh-shell:bash -*-
+# shellcheck shell=bash
+
+#> ate_exit_on_error
+
 ate_exit_on_error()
 {
     local -i exval="$?"
     if [ "$exval" -ne 0 ]; then
         printf $'ate error at line %d of script %s:\n' \
                $(( "${BASH_LINENO[0]}" - 1 )) \
-               "${BASH_SOURCE[1]}"
-        printf $'   \e[31;1m%s\e[m\n' "$ATE_ERROR"
+               "${BASH_SOURCE[1]}" >&2
+        printf $'   \e[31;1m%s\e[m\n' "$ATE_ERROR" >&2
         exit 1
     fi
 }
